### ISSUE TITLE
have a problem to install tensorflow 2 on windows 10

### ISSUE THREAD

**Issue by todokku** [ozankaraali/yolov3-recaptcha#1]
Hi Ozan,
Im have a problem to install tensorflow 2 on windows 10
& your code overview is simple like ubuntu code ,
please telll me one reason to solve the problem to run code on windows 10 
finest regards to you & backstage team 
waiting for your response
goodbye

**Comment by ozankaraali** [comment]
Hello todokku,
I saw the official installation steps and this would be the proper way to install. However I think that tensorflow is available via pip. Therefore, here is a tutorial that you could try: https://automaticaddison.com/how-to-install-tensorflow-2-on-windows-10/
Try it and let me know.
Best,
Ozan

**Comment by ozankaraali** [comment]
Closing the issue, if you need it, feel free to reopen.
