### ISSUE TITLE
cpu doesn't support Tensorflow AVX instructions

### ISSUE THREAD

**Issue by todokku** [ozankaraali/yolov3-recaptcha#3]
Hi Ozan ,
I'm installing tensorflow 2 & 2.1 with anaconda env python 3.6 & tensorflow not work because my cpu doesn't support Tensorflow AVX instructions (intel core i7 930) & my graphic is very low for cuda core render & gpu usage (nvidia 465 gtx) , after that  im insalling latest version support non-avx instruction cpu's (tensorflow==1.5) but after run selenium demo code (selenium_demo.py) getting error in set $path for chrome webdriver.exe , please re-check code syntax & make it friendly for tensorflow 1.5 on windows 10 using anaconda env.
wating for your commit changes to fix :)
finest regards
goodbye

**Comment by ozankaraali** [comment]
Hi @todokku ,
Tensorflow 2 is designed to work with different sets of CPUs and GPUs in only one package. Therefore if your GPU supports a little bit of tensors, it would work on GPU, or if not on your CPU. AVX is optimized instructions for CPU and Tensorflow does not need to use AVX-compatible CPUs specifically. Therefore here you can find Tensorflow without AVX: https://github.com/fo40225/tensorflow-windows-wheel

In addition $PATH problem shows that you did not put webdriver on your system path. Here is an example how you would add webdriver on your path: https://docs.alfresco.com/4.2/tasks/fot-addpath.html

As a result, I would not recommend using that computer for machine learning projects, but if you still want to use, you can do a proper CPU demo in 15-20 seconds waiting time with proper installation.

I have no plans to make it fully compatible with Tensorflow 1.5 (but I assume that it may work on even Tensorflow 1.5 systems, no guarantees.)

Let me know if you have any further questions. In a week of inactivity, issue will be closed.
Regards
Ozan
