### ISSUE TITLE
making it click?

### ISSUE THREAD

**Issue by NFReal** [ozankaraali/yolov3-recaptcha#4]
Hey Ozankaraali,

How would I get the positions of the bounding boxes so I can use selenium to click on it?
Would love to hear back!
Hope you're doing well in these times :)

**Comment by ozankaraali** [comment]
Hello, I’m fine, thanks for asking and I hope you’re well too.
You could take screenshot of the whole display, then try to find where the captcha box is and click, an option. Or you could try to understand which boxes need to be clicked via extending Tensorflow’s output and then applying to Selenium’s divs that could counterpart to your output, another option I could think. PR’s are welcome, if you want to contribute.

**Comment by ozankaraali** [comment]
Closed due to inactivity, if you want to contribute, PRs welcome.
