### ISSUE TITLE
ValueError: Layer weight shape (32,) not compatible with provided weight shape (64,)

### ISSUE THREAD

**Issue by mrboogie90** [ozankaraali/yolov3-recaptcha#5]
When I run the demo file image_demo.py, I get the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-aa3c99b00768> in <module>()
     38 
     39 model = tf.keras.Model(input_layer, bbox_tensors)
---> 40 utils.load_weights(model, "./yolov3.weights")
     41 model.summary()
     42 

/content/drive/My Drive/yolov3-recaptcha/core/utils.py in load_weights(model, weights_file)
     53         if i not in [58, 66, 74]:
     54             conv_layer.set_weights([conv_weights])
---> 55             bn_layer.set_weights(bn_weights)
     56         else:
     57             conv_layer.set_weights([conv_weights, conv_bias])

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in set_weights(self, weights)
   1824           raise ValueError(
   1825               'Layer weight shape %s not compatible with provided weight '
-> 1826               'shape %s' % (ref_shape, weight.shape))
   1827         weight_value_tuples.append((param, weight))
   1828         weight_index += 1

ValueError: Layer weight shape (32,) not compatible with provided weight shape (64,)

**Comment by ozankaraali** [comment]
I could not reproduce it.
Do a fresh git clone, use new venv/conda and run image_demo.py without modifying.
![tmp09w152fg](https://user-images.githubusercontent.com/19486728/89822209-7ed95a00-db58-11ea-89b5-01159bfb9ca7.png)
